import { existsSync } from 'fs';

function escapeActionValue(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r?\n/g, ' ');
}

function escapeRegexPattern(value) {
  return String(value ?? '').replace(/\r?\n/g, '');
}

/**
 * ModSecurity Engine Integration
 * 
 * This module provides ModSecurity integration for ATRAVAD WAF.
 * It generates comprehensive ModSecurity configurations and provides
 * utilities for rule management and OWASP CRS integration.
 */

/**
 * Generate comprehensive ModSecurity configuration from policy
 * @param {Object} policy - Policy object with protection settings
 * @param {Object} options - Additional configuration options
 * @returns {string} Complete ModSecurity configuration
 */
export function generateModSecurityConfig(policy, options = {}) {
  const {
    includeOWASPCRS = true,
    ruleIdBase: initialRuleIdBase = 100000,
    mode = 'prevention', // 'detection' or 'prevention'
    paranoiaLevel = 4,
  } = options;

  // Use a mutable variable for ruleIdBase since we need to increment it
  let ruleIdBase = initialRuleIdBase;

  let config = '# ModSecurity Configuration\n';
  config += '# Generated by ATRAVAD WAF\n';
  config += `# Generated: ${new Date().toISOString()}\n\n`;

  // Basic ModSecurity configuration
  config += '# Basic ModSecurity Configuration\n';
  config += 'SecRuleEngine On\n';
  config += `SecRequestBodyAccess On\n`;
  config += `SecResponseBodyAccess On\n`;
  config += `SecResponseBodyMimeType text/plain text/html text/xml application/json application/javascript\n`;
  config += `SecResponseBodyLimit 524288\n`;
  config += `SecRequestBodyLimit 13107200\n`;
  config += `SecRequestBodyNoFilesLimit 131072\n`;
  config += `SecRequestBodyLimitAction Reject\n`;
  config += `SecPcreMatchLimit 1000\n`;
  config += `SecPcreMatchLimitRecursion 1000\n`;
  config += `SecTmpDir /tmp/\n`;
  config += `SecDataDir /tmp/\n`;
  config += `SecUploadDir /tmp/\n`;
  config += `SecUploadFileMode 0600\n`;
  config += `SecTmpSaveUploadedFiles On\n\n`;

  // OWASP CRS Integration with Enhanced Configuration
  if (includeOWASPCRS) {
    config += '# OWASP Core Rule Set (CRS) Integration\n';
    config += '# OWASP CRS Setup Configuration\n';
    config += `# Paranoia Level: ${paranoiaLevel}\n`;
    config += '# Higher paranoia increases attack coverage and false-positive risk\n';
    config += `SecAction "id:900000,phase:1,pass,nolog,setvar:tx.paranoia_level=${paranoiaLevel},setvar:tx.executing_paranoia_level=${paranoiaLevel}"\n`;
    config += 'SecAction "id:900001,phase:1,pass,nolog,setvar:tx.inbound_anomaly_score_threshold=5,setvar:tx.outbound_anomaly_score_threshold=4"\n';
    config += 'Include /etc/modsecurity/crs-setup.conf\n';
    config += '\n# OWASP CRS Rule Sets\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-901-INITIALIZATION.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-905-COMMON-EXCEPTIONS.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-910-IP-REPUTATION.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-911-METHOD-ENFORCEMENT.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-912-DOS-PROTECTION.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-913-SCANNER-DETECTION.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-921-PROTOCOL-ATTACK.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf\n';
    config += 'Include /etc/modsecurity/rules/REQUEST-949-BLOCKING-EVALUATION.conf\n';
    config += 'Include /etc/modsecurity/rules/RESPONSE-950-DATA-LEAKAGES.conf\n';
    config += 'Include /etc/modsecurity/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf\n';
    config += 'Include /etc/modsecurity/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf\n';
    config += 'Include /etc/modsecurity/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf\n';
    config += 'Include /etc/modsecurity/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf\n';
    config += 'Include /etc/modsecurity/rules/RESPONSE-959-BLOCKING-EVALUATION.conf\n';
    config += 'Include /etc/modsecurity/rules/RESPONSE-980-CORRELATION.conf\n';
    config += '\n# Custom rules below will complement CRS\n\n';
  }

  // Always-on scanner/signature blocking to catch common security tooling
  // even when optional bot-detection features are not enabled on a policy.
  config += generateKnownScannerBlockRules(ruleIdBase);
  ruleIdBase += 100;

  // SQL Injection Protection
  if (policy.sqlInjection) {
    config += generateSQLInjectionRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // XSS Protection
  if (policy.xss) {
    config += generateXSSRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // File Upload Protection
  if (policy.fileUpload) {
    config += generateFileUploadRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Path Traversal Protection
  if (policy.pathTraversal) {
    config += generatePathTraversalRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Remote Code Execution Protection
  if (policy.rce) {
    config += generateRCERules(ruleIdBase);
    ruleIdBase += 100;
  }

  // CSRF Protection
  if (policy.csrf) {
    config += generateCSRFRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Session Fixation Protection
  if (policy.sessionFixation) {
    config += generateSessionFixationRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // SSRF (Server-Side Request Forgery) Protection
  if (policy.ssrf) {
    config += generateSSRFRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // XXE (XML External Entity) Protection
  if (policy.xxe) {
    config += generateXXERules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Authentication Bypass Protection
  if (policy.authBypass) {
    config += generateAuthBypassRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Insecure Direct Object Reference Protection
  if (policy.idor) {
    config += generateIDORRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Security Misconfiguration Detection
  if (policy.securityMisconfig) {
    config += generateSecurityMisconfigRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Sensitive Data Exposure Protection
  if (policy.sensitiveDataExposure) {
    config += generateSensitiveDataExposureRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Broken Access Control Protection
  if (policy.brokenAccessControl) {
    config += generateBrokenAccessControlRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // Rate Limiting
  if (policy.rateLimiting) {
    config += generateRateLimitingRules(ruleIdBase, policy.rateLimiting);
    ruleIdBase += 100;
  }

  // Security Headers
  if (policy.securityHeaders) {
    config += generateSecurityHeadersRules(ruleIdBase);
    ruleIdBase += 100;
  }

  // IP Access Control (Whitelisting/Blacklisting)
  if (policy.ipAccessControl) {
    config += generateIPAccessControlRules(ruleIdBase, policy.ipAccessControl);
    ruleIdBase += 100;
  }

  // Geographic Blocking
  if (policy.geoBlocking) {
    config += generateGeoBlockingRules(ruleIdBase, policy.geoBlocking);
    ruleIdBase += 100;
  }

  // Advanced Rate Limiting (Per-Endpoint, Per-User)
  if (policy.advancedRateLimiting) {
    config += generateAdvancedRateLimitingRules(ruleIdBase, policy.advancedRateLimiting);
    ruleIdBase += 100;
  }

  // Bot Detection and Mitigation
  if (policy.botDetection) {
    config += generateBotDetectionRules(ruleIdBase, policy.botDetection);
    ruleIdBase += 100;
  }

  // Advanced File Upload Validation
  if (policy.advancedFileUpload) {
    config += generateAdvancedFileUploadRules(ruleIdBase, policy.advancedFileUpload);
    ruleIdBase += 100;
  }

  // API-Specific Protections
  if (policy.apiProtection) {
    config += generateAPIProtectionRules(ruleIdBase, policy.apiProtection);
    ruleIdBase += 100;
  }

  // Exception Handling (Rule Exclusions)
  if (policy.exceptions && Array.isArray(policy.exceptions)) {
    config += generateExceptionRules(ruleIdBase, policy.exceptions);
    ruleIdBase += 100;
  }

  // Virtual Patching (CVE-Specific Rules)
  if (policy.virtualPatching && Array.isArray(policy.virtualPatching)) {
    config += generateVirtualPatchingRules(ruleIdBase, policy.virtualPatching);
    ruleIdBase += 100;
  }

  // Custom Rules
  if (policy.customRules && Array.isArray(policy.customRules)) {
    config += '# Custom Rules\n';
    policy.customRules.forEach((rule, index) => {
      config += generateCustomRule(rule, ruleIdBase + index);
    });
  }

  // Logging Configuration (Enhanced)
  config += '\n# Enhanced Logging Configuration\n';
  config += 'SecAuditEngine RelevantOnly\n';
  config += 'SecAuditLogRelevantStatus "^(?:5|4(?!04))"\n';
  config += 'SecAuditLogParts ABIJDEFHZ\n';
  config += 'SecAuditLogType Serial\n';
  config += `SecAuditLog /var/log/modsec_audit.log\n`;
  config += 'SecAuditLogStorageDir /var/log/modsec_audit/\n';
  config += 'SecAuditLogFileMode 0600\n';
  config += 'SecAuditLogDirMode 0750\n';
  config += 'SecAuditLogDirPermissions 0750\n\n';

  // Error Handling
  config += '# Error Handling\n';
  if (mode === 'prevention') {
    config += `SecDefaultAction "phase:1,log,auditlog,deny,status:403"\n`;
    config += `SecDefaultAction "phase:2,log,auditlog,deny,status:403"\n`;
  } else {
    config += `SecDefaultAction "phase:1,log,auditlog,pass"\n`;
    config += `SecDefaultAction "phase:2,log,auditlog,pass"\n`;
  }
  config += '\n';

  return config;
}

/**
 * Generate SQL Injection detection rules
 */
function generateSQLInjectionRules(ruleIdBase) {
  let rules = '# SQL Injection Protection Rules\n';
  
  // Primary SQL Injection detection
  rules += `SecRule ARGS "@detectSQLi" \\
    "id:${ruleIdBase},phase:2,block,msg:'SQL Injection Attack Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-sqli',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/SQL_INJECTION',\\
    ver:'OWASP_CRS/3.3.0',\\
    rev:'1',\\
    maturity:'9',\\
    accuracy:'9',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,t:removeNulls,\\
    capture,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.sql_injection_score=+1',\\
    setvar:'tx.paranoid_mode=1'"\n\n`;

  // SQL Injection in request body
  rules += `SecRule REQUEST_BODY "@detectSQLi" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'SQL Injection in Request Body',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'attack-sqli',\\
    t:none,t:urlDecodeUni,t:removeNulls,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // SQL keywords detection (Enhanced pattern)
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx (?i)(?:\\b(?:(?:s(?:elect\\b.{0,40}\\b(?:(?:(?:(?:length|count|top)\\b.{0,40}\\bfrom|from\\b.{0,40}\\bwhere)|.*?\\b(?:d(?:ump\\b.*\\bfrom|ata_type)|(?:to_(?:num|char)|inst(?:r|ance_of))\\b)|[^\\s]*\\b(?:n(?:vl|extval)|[^\\s]*\\b(?:asc|desc)\\b.*\\b(?:chr|char))|.*?\\b(?:group|order)\\b.*\\bby\\b.{0,40}\\b(?:chr|char|ascii|substring|substr|truncate|cast|convert|concat|concat_ws))|.*?\\b(?:union|select|having|group|order)\\b.*\\b(?:select|from|where|group|order|having|limit|offset|union|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b|.*?\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b.*\\b(?:select|from|where|group|order|having|limit|offset|union|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b|.*?\\b(?:select|from|where|group|order|having|limit|offset|union|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b.*\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b|.*?\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b.*\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b|.*?\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b.*\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b))|(?:'\\s*(?:or|and)\\s*['\\\"]?\\d+['\\\"]?\\s*=\\s*['\\\"]?\\d+|'\\s*(?:or|and)\\s*['\\\"]?[a-z]\\w*['\\\"]?\\s*=\\s*['\\\"]?[a-z]\\w*|'\\s*(?:or|and)\\s*'1'\\s*=\\s*'1|'\\s*(?:or|and)\\s*1\\s*=\\s*1)" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'SQL Injection Attack: Common SQL Injection Testing Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-sqli',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/SQL_INJECTION',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,t:removeNulls,\\
    capture,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.sql_injection_score=+1'"\n\n`;

  // SQL comment detection
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx (?i)(?:--|#|/\\*|\\*/|;\\s*--|;\\s*#)" \\
    "id:${ruleIdBase + 3},phase:2,block,msg:'SQL Injection Attack: SQL Comment Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-sqli',\\
    tag:'OWASP_CRS',\\
    t:none,t:urlDecodeUni,t:removeNulls,\\
    chain"\n`;
  rules += `SecRule MATCHED_VAR "@rx (?i)(?:select|union|insert|update|delete|drop|create|alter|exec|execute)" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.sql_injection_score=+1'"\n\n`;

  // Raw URI / query-string SQLi probes (helps when upstream parsing does not
  // populate ARGS the way we expect for edge-only inspection).
  rules += `SecRule REQUEST_URI|QUERY_STRING "@rx (?i)(?:union(?:\\s+all)?\\s+select|select\\b.{0,80}\\bfrom|(?:^|[?&][^=]{0,48}=)['\\\"]?\\s*(?:or|and)\\s*['\\\"]?(?:1|true|[a-z]\\w*)['\\\"]?\\s*=\\s*['\\\"]?(?:1|true|[a-z]\\w*)|sleep\\s*\\(|benchmark\\s*\\(|waitfor\\s+delay|information_schema|@@version)" \\
    "id:${ruleIdBase + 4},phase:2,block,msg:'SQL Injection Attack: Raw URI Pattern Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-sqli',\\
    t:none,t:urlDecodeUni,t:lowercase,t:removeNulls,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.sql_injection_score=+1'"\n\n`;

  return rules;
}

/**
 * Generate XSS protection rules
 */
function generateXSSRules(ruleIdBase) {
  let rules = '# XSS (Cross-Site Scripting) Protection Rules\n';
  
  // Primary XSS detection
  rules += `SecRule ARGS "@detectXSS" \\
    "id:${ruleIdBase},phase:2,block,msg:'XSS Attack Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-xss',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/XSS',\\
    ver:'OWASP_CRS/3.3.0',\\
    rev:'1',\\
    maturity:'9',\\
    accuracy:'9',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,t:removeNulls,\\
    capture,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.xss_score=+1'"\n\n`;

  // Script tag detection
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx (?i)(?:<script[^>]*>.*?</script>|<script[^>]*>|javascript:|vbscript:|onload=|onerror=|onclick=|onmouseover=|onfocus=|onblur=)" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'XSS Attack: Script Tag Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-xss',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,t:removeNulls,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // Event handler detection
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES "@rx (?i)(?:on(?:load|error|click|mouseover|focus|blur|change|submit|reset|select|abort|keydown|keypress|keyup|mousedown|mousemove|mouseout|mouseup|resize|scroll|unload))\\s*=" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'XSS Attack: Event Handler Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-xss',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // Raw URI / query-string XSS probes.
  rules += `SecRule REQUEST_URI|QUERY_STRING "@rx (?i)(?:<script[^>]*>|</script>|javascript:|vbscript:|data:text/html|on(?:load|error|click|mouseover|focus|blur)\\s*=|%3cscript|%3c/svg|%3cimg)" \\
    "id:${ruleIdBase + 3},phase:2,block,msg:'XSS Attack: Raw URI Pattern Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-xss',\\
    t:none,t:urlDecodeUni,t:lowercase,t:removeNulls,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.xss_score=+1'"\n\n`;

  return rules;
}

/**
 * Generate file upload protection rules
 */
function generateFileUploadRules(ruleIdBase) {
  let rules = '# File Upload Protection Rules\n';
  
  // Dangerous file extensions
  rules += `SecRule FILES_TMPNAMES|FILES_NAMES "@rx \\.(?:php|phtml|php3|php4|php5|phps|cgi|exe|pl|asp|aspx|jsp|sh|bat|cmd|com|scr|vbs|js|jar|war|ear|class|py|rb|ps1|psm1|psd1|sh|bash|zsh|fish|ksh|csh|tcsh|dmg|app|deb|rpm|msi|dll|so|dylib|bin|run|out|elf)$" \\
    "id:${ruleIdBase},phase:2,block,msg:'Dangerous File Upload Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-fileupload',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/FILE_UPLOAD',\\
    t:none,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // File size limits
  rules += `SecRule &FILES "@gt 10" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'Too Many Files Uploaded',\\
    severity:'WARNING',\\
    tag:'attack-fileupload',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  // File content type validation
  rules += `SecRule FILES "@rx \\.(?:jpg|jpeg|png|gif|pdf|doc|docx|xls|xlsx|txt|zip|rar)$" \\
    "id:${ruleIdBase + 2},phase:2,pass,msg:'Allowed File Type',\\
    t:none,t:lowercase"\n\n`;

  return rules;
}

/**
 * Generate path traversal protection rules
 */
function generatePathTraversalRules(ruleIdBase) {
  let rules = '# Path Traversal Protection Rules\n';
  
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_URI|QUERY_STRING|REQUEST_HEADERS|XML:/* "@rx (?:(?:\\.\\.(?:%2f|%5c|/|\\\\))|(?:(?:%2f|%5c|/|\\\\)\\.\\.(?:%2f|%5c|/|\\\\))|(?:^(?:%2f|%5c|/|\\\\)\\.\\.(?:%2f|%5c|/|\\\\)))" \\
    "id:${ruleIdBase},phase:2,block,msg:'Path Traversal Attack Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-path-traversal',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/PATH_TRAVERSAL',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  rules += `SecRule REQUEST_URI|QUERY_STRING "@rx (?i)(?:/etc/passwd|/etc/shadow|/proc/self/environ|\\\\windows\\\\win\\.ini|/windows/system32|boot\\.ini|%2fetc%2fpasswd|%2e%2e%2f|%2e%2e%5c)" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'Path Traversal Attack: Sensitive File Probe Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-path-traversal',\\
    t:none,t:urlDecodeUni,t:lowercase,t:removeNulls,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  return rules;
}

function generateKnownScannerBlockRules(ruleIdBase) {
  let rules = '# Known Scanner / Tool Signature Blocking Rules\n';

  rules += `SecRule REQUEST_HEADERS:User-Agent "@rx (?i)(?:sqlmap|nikto|wafw00f|acunetix|netsparker|nessus|openvas|nmap\\s+scripting\\s+engine|nmap|masscan|zgrab|dirbuster|gobuster|ffuf|wpscan|nuclei|jaeles|zaproxy|burp)" \\
    "id:${ruleIdBase},phase:1,block,msg:'Scanner Detection: Known Security Tool User-Agent Detected',\\
    logdata:'User-Agent: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'scanner-detection',\\
    tag:'attack-recon',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  rules += `SecRule REQUEST_URI|QUERY_STRING "@rx (?i)(?:/\\.git/|/\\.env(?:$|[?&#])|/wp-admin|/wp-login\\.php|/phpmyadmin|/server-status|/actuator|/\\.svn/|/\\.hg/)" \\
    "id:${ruleIdBase + 1},phase:1,block,msg:'Scanner Detection: Reconnaissance Path Probe Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'scanner-detection',\\
    tag:'attack-recon',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate Remote Code Execution protection rules
 */
function generateRCERules(ruleIdBase) {
  let rules = '# Remote Code Execution (RCE) Protection Rules\n';
  
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx (?i)(?:\\b(?:(?:s(?:elect\\b.*\\b(?:length|count|top)\\b.*\\bfrom|from\\b.*\\bwhere)|.*?\\b(?:d(?:ump\\b.*\\bfrom|ata_type)|(?:to_(?:num|char)|inst(?:r|ance_of))\\b)|[^\\s]*\\b(?:n(?:vl|extval)|[^\\s]*\\b(?:asc|desc)\\b.*\\b(?:chr|char))|.*?\\b(?:group|order)\\b.*\\bby\\b.*\\b(?:chr|char|ascii|substring|substr|truncate|cast|convert|concat|concat_ws))|.*?\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b.*\\b(?:select|from|where|group|order|having|limit|offset|union|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b|.*?\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b.*\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b|.*?\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b.*\\b(?:union|select|insert|update|delete|create|alter|drop|exec|execute|script|javascript|vbscript|onload|onerror)\\b)|(?:\\b(?:cmd|command|exec|execute|system|shell|bash|sh|powershell|python|perl|ruby|php|eval|call_user_func|assert|preg_replace|create_function|file_get_contents|file_put_contents|fopen|fwrite|fread|include|require|include_once|require_once|passthru|proc_open|popen|shell_exec|system|exec|eval|assert|call_user_func|preg_replace|create_function)\\b)" \\
    "id:${ruleIdBase},phase:2,block,msg:'Remote Code Execution Attempt Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-rce',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/RCE',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate CSRF (Cross-Site Request Forgery) protection rules
 */
function generateCSRFRules(ruleIdBase) {
  let rules = '# CSRF (Cross-Site Request Forgery) Protection Rules\n';

  // Capture host for same-origin checks.
  rules += `SecAction "id:${ruleIdBase},phase:1,pass,nolog,t:none,setvar:'tx.allowed_host=%{request_headers.host}'"\n\n`;

  // Require same-site context for state-changing browser requests.
  rules += `SecRule REQUEST_METHOD "@rx ^(?:POST|PUT|DELETE|PATCH)$" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'CSRF Protection: Missing Origin and Referer Headers',\\
    severity:'CRITICAL',\\
    tag:'attack-csrf',\\
    t:none,\\
    chain"\n`;
  rules += `SecRule &REQUEST_HEADERS:Origin "@eq 0" "t:none,chain"\n`;
  rules += `SecRule &REQUEST_HEADERS:Referer "@eq 0" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.csrf_score=+1'"\n\n`;

  // Origin header must match the protected host when present.
  rules += `SecRule REQUEST_METHOD "@rx ^(?:POST|PUT|DELETE|PATCH)$" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'CSRF Protection: Origin Header Validation Failed',\\
    logdata:'Origin: %{REQUEST_HEADERS.Origin}',\\
    severity:'CRITICAL',\\
    tag:'attack-csrf',\\
    t:none,\\
    chain"\n`;
  rules += `SecRule &REQUEST_HEADERS:Origin "@gt 0" "t:none,chain"\n`;
  rules += `SecRule REQUEST_HEADERS:Origin "!@contains %{tx.allowed_host}" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.csrf_score=+1'"\n\n`;

  // Referer fallback when Origin is absent.
  rules += `SecRule REQUEST_METHOD "@rx ^(?:POST|PUT|DELETE|PATCH)$" \\
    "id:${ruleIdBase + 3},phase:2,block,msg:'CSRF Protection: Referer Header Validation Failed',\\
    logdata:'Referer: %{REQUEST_HEADERS.Referer}',\\
    severity:'WARNING',\\
    tag:'attack-csrf',\\
    t:none,\\
    chain"\n`;
  rules += `SecRule &REQUEST_HEADERS:Origin "@eq 0" "t:none,chain"\n`;
  rules += `SecRule &REQUEST_HEADERS:Referer "@gt 0" "t:none,chain"\n`;
  rules += `SecRule REQUEST_HEADERS:Referer "!@contains %{tx.allowed_host}" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  // Token validation only for form-style submissions.
  rules += `SecRule REQUEST_METHOD "@rx ^(?:POST|PUT|DELETE|PATCH)$" \\
    "id:${ruleIdBase + 4},phase:2,block,msg:'CSRF Protection: Missing Form Security Token',\\
    severity:'CRITICAL',\\
    tag:'attack-csrf',\\
    t:none,\\
    chain"\n`;
  rules += `SecRule REQUEST_HEADERS:Content-Type "@rx (?i)^(?:application/x-www-form-urlencoded|multipart/form-data)" "t:none,chain"\n`;
  rules += `SecRule &ARGS:csrf_token "@eq 0" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}',\\
    setvar:'tx.csrf_score=+1'"\n\n`;

  return rules;
}

/**
 * Generate Session Fixation protection rules
 */
function generateSessionFixationRules(ruleIdBase) {
  let rules = '# Session Fixation Protection Rules\n';
  
  // Block only known session identifier cookie names.
  // Generic names containing "session" such as "atra_session" are valid in many
  // apps and should not be treated as fixation attempts by themselves.
  rules += `SecRule REQUEST_COOKIES_NAMES "@rx (?i)^(?:sessionid|session_id|jsessionid|phpsessid|aspsessionid|asp\\.net_sessionid)$" \\
    "id:${ruleIdBase},phase:2,block,msg:'Session Fixation: Suspicious Session ID Pattern Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'WARNING',\\
    tag:'attack-session-fixation',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/SESSION_FIXATION',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  // Multiple session IDs detection
  rules += `SecRule &REQUEST_COOKIES "@gt 5" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'Session Fixation: Too Many Session Cookies Detected',\\
    severity:'WARNING',\\
    tag:'attack-session-fixation',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate SSRF (Server-Side Request Forgery) protection rules
 */
function generateSSRFRules(ruleIdBase) {
  let rules = '# SSRF (Server-Side Request Forgery) Protection Rules\n';
  
  // Internal IP address detection
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx (?i)(?:localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0|10\\.(?:\\d{1,3}\\.){2}\\d{1,3}|172\\.(?:1[6-9]|2\\d|3[01])\\.(?:\\d{1,3}\\.)\\d{1,3}|192\\.168\\.(?:\\d{1,3}\\.)\\d{1,3}|169\\.254\\.(?:\\d{1,3}\\.)\\d{1,3})" \\
    "id:${ruleIdBase},phase:2,block,msg:'SSRF Attack: Internal IP Address Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-ssrf',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/SSRF',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // URL scheme detection (file://, gopher://, etc.)
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx (?i)(?:file://|gopher://|dict://|ldap://|ldaps://|jar://|php://|zlib://|data://|expect://|ssh2://|rar://|ogg://|tftp://)" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'SSRF Attack: Dangerous URL Scheme Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-ssrf',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // Metadata endpoint detection (AWS, Azure, GCP)
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx (?i)(?:169\\.254\\.169\\.254|metadata\\.googleapis\\.com|metadata\\.azure\\.com|169\\.254\\.169\\.254)" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'SSRF Attack: Cloud Metadata Endpoint Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-ssrf',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate XXE (XML External Entity) protection rules
 */
function generateXXERules(ruleIdBase) {
  let rules = '# XXE (XML External Entity) Protection Rules\n';
  
  // External entity declaration detection
  rules += `SecRule REQUEST_BODY|XML "@rx (?i)(?:<!ENTITY\\s+[^>]*SYSTEM\\s+[^>]*>|<!DOCTYPE\\s+[^>]*\\[\\s*<!ENTITY)" \\
    "id:${ruleIdBase},phase:2,block,msg:'XXE Attack: External Entity Declaration Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'attack-xxe',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/XXE',\\
    t:none,t:urlDecodeUni,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // XML external entity reference
  rules += `SecRule REQUEST_BODY|XML "@rx (?i)(?:&[a-zA-Z_][a-zA-Z0-9_]*;|%[a-zA-Z_][a-zA-Z0-9_]*;)" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'XXE Attack: External Entity Reference Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'attack-xxe',\\
    t:none,t:urlDecodeUni,\\
    chain"\n`;
  rules += `SecRule REQUEST_BODY|XML "@rx (?i)(?:file://|http://|https://|ftp://|php://|zlib://|data://)" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // XML processing instruction detection
  rules += `SecRule REQUEST_BODY|XML "@rx (?i)(?:<\\?xml[^>]*encoding\\s*=\\s*[^>]*>|<!DOCTYPE[^>]*SYSTEM[^>]*>)" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'XXE Attack: Suspicious XML Processing Instruction',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'WARNING',\\
    tag:'attack-xxe',\\
    t:none,t:urlDecodeUni,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate Authentication Bypass protection rules
 */
function generateAuthBypassRules(ruleIdBase) {
  let rules = '# Authentication Bypass Protection Rules\n';
  
  // SQL injection in authentication parameters
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES "@rx (?i)(?:user(?:name|id|_id|_name)?|pass(?:word|wd|_word|_wd)?|login|auth|token|session)" \\
    "id:${ruleIdBase},phase:2,block,msg:'Authentication Bypass: SQL Injection in Auth Parameters',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-auth-bypass',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/WEB_ATTACK/AUTH_BYPASS',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    chain"\n`;
  rules += `SecRule MATCHED_VAR "@detectSQLi" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // Authentication bypass attempts
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES "@rx (?i)(?:admin'\\s*--|admin'\\s*#|admin'\\s*;|'\\s*OR\\s*'1'\\s*=\\s*'1|'\\s*OR\\s*1\\s*=\\s*1|'\\s*UNION\\s*SELECT|'\\s*OR\\s*'x'\\s*=\\s*'x)" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'Authentication Bypass: Common Bypass Pattern Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-auth-bypass',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // Weak authentication patterns
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES "@rx (?i)(?:password\\s*=\\s*['\\\"]?admin['\\\"]?|password\\s*=\\s*['\\\"]?12345|password\\s*=\\s*['\\\"]?password)" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'Authentication Bypass: Weak Password Pattern Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'WARNING',\\
    tag:'attack-auth-bypass',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate IDOR (Insecure Direct Object Reference) protection rules
 */
function generateIDORRules(ruleIdBase) {
  let rules = '# IDOR (Insecure Direct Object Reference) Protection Rules\n';
  
  // Sequential ID detection
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME "@rx (?i)(?:id|user_id|account_id|order_id|transaction_id|file_id|document_id)\\s*=\\s*(?:\\d{1,6}|[a-f0-9]{8,32})" \\
    "id:${ruleIdBase},phase:2,pass,msg:'IDOR Protection: Direct Object Reference Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'INFO',\\
    tag:'security-idor',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.idor_detected=1'"\n\n`;

  // Path traversal in object references
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME "@rx (?i)(?:/etc/passwd|/etc/shadow|/proc/self/environ|/windows/system32|/etc/hosts|/var/log)" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'IDOR Attack: System File Access Attempt',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'attack-idor',\\
    tag:'OWASP_CRS',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate Security Misconfiguration detection rules
 */
function generateSecurityMisconfigRules(ruleIdBase) {
  let rules = '# Security Misconfiguration Detection Rules\n';
  
  // Exposed configuration files
  rules += `SecRule REQUEST_FILENAME "@rx (?i)(?:\\.(?:git|svn|hg|bzr|env|config|conf|ini|log|bak|backup|old|swp|tmp|temp|test|dev|staging|production)\\.|/\\.(?:git|svn|hg|bzr|env|config|conf|ini|log|bak|backup|old|swp|tmp|temp|test|dev|staging|production)/)" \\
    "id:${ruleIdBase},phase:2,block,msg:'Security Misconfiguration: Exposed Configuration File Access Attempt',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'security-misconfig',\\
    tag:'OWASP_CRS',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // Default credentials detection
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES "@rx (?i)(?:admin:admin|root:root|guest:guest|user:user|test:test|demo:demo|administrator:password)" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'Security Misconfiguration: Default Credentials Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'WARNING',\\
    tag:'security-misconfig',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  // Debug/development endpoints
  rules += `SecRule REQUEST_FILENAME|REQUEST_URI "@rx (?i)(?:/debug|/test|/dev|/staging|/admin|/phpinfo|/info\\.php|/test\\.php|/dev\\.php|/console|/shell|/cmd)" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'Security Misconfiguration: Debug/Development Endpoint Access',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'WARNING',\\
    tag:'security-misconfig',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate Sensitive Data Exposure protection rules
 */
function generateSensitiveDataExposureRules(ruleIdBase) {
  let rules = '# Sensitive Data Exposure Protection Rules\n';
  
  // Credit card number detection in responses
  rules += `SecRule RESPONSE_BODY "@rx \\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3[0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\\b" \\
    "id:${ruleIdBase},phase:4,block,msg:'Sensitive Data Exposure: Credit Card Number Detected in Response',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'security-sensitive-data',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/DATA_LEAKAGE/CREDIT_CARD',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // SSN detection in responses
  rules += `SecRule RESPONSE_BODY "@rx \\b\\d{3}-?\\d{2}-?\\d{4}\\b" \\
    "id:${ruleIdBase + 1},phase:4,block,msg:'Sensitive Data Exposure: SSN Detected in Response',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'security-sensitive-data',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // API keys and tokens in responses
  rules += `SecRule RESPONSE_BODY "@rx (?i)(?:api[_-]?key|secret[_-]?key|access[_-]?token|auth[_-]?token|bearer[_-]?token|private[_-]?key|public[_-]?key)\\s*[:=]\\s*['\\\"]?[a-zA-Z0-9]{20,}['\\\"]?" \\
    "id:${ruleIdBase + 2},phase:4,block,msg:'Sensitive Data Exposure: API Key/Token Detected in Response',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'security-sensitive-data',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  // Database connection strings
  rules += `SecRule RESPONSE_BODY "@rx (?i)(?:mysql://|postgresql://|mongodb://|sqlserver://|oracle://|jdbc:)[^\\s'\\\"]+" \\
    "id:${ruleIdBase + 3},phase:4,block,msg:'Sensitive Data Exposure: Database Connection String Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'security-sensitive-data',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate Broken Access Control protection rules
 */
function generateBrokenAccessControlRules(ruleIdBase) {
  let rules = '# Broken Access Control Protection Rules\n';
  
  // Directory traversal in authorization headers
  rules += `SecRule REQUEST_HEADERS|ARGS|ARGS_NAMES "@rx (?i)(?:/admin|/administrator|/root|/api/admin|/api/root|/internal|/private|/secure)" \\
    "id:${ruleIdBase},phase:2,pass,msg:'Access Control: Admin/Privileged Endpoint Access Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'INFO',\\
    tag:'security-access-control',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.privileged_access=1'"\n\n`;

  // Unauthorized HTTP methods
  rules += `SecRule REQUEST_METHOD "@rx ^(?:TRACE|TRACK|CONNECT|OPTIONS)$" \\
    "id:${ruleIdBase + 1},phase:2,block,msg:'Access Control: Unauthorized HTTP Method',\\
    logdata:'Method: %{MATCHED_VAR}',\\
    severity:'WARNING',\\
    tag:'security-access-control',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  // Privilege escalation attempts
  rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES "@rx (?i)(?:role\\s*=\\s*['\\\"]?admin|permission\\s*=\\s*['\\\"]?all|level\\s*=\\s*['\\\"]?999|is_admin\\s*=\\s*['\\\"]?true|is_superuser\\s*=\\s*['\\\"]?true)" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'Access Control: Privilege Escalation Attempt Detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'security-access-control',\\
    tag:'OWASP_CRS',\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate Security Headers rules
 */
function generateSecurityHeadersRules(ruleIdBase) {
  let rules = '# Security Headers Rules\n';

  // The proxy/native Rules.add() path cannot apply Apache-specific setenv actions.
  // Keep only passive detection rules so generated policies stay loadable.
  rules += `SecRule RESPONSE_HEADERS:X-Frame-Options "@eq 0" \\
    "id:${ruleIdBase},phase:4,pass,msg:'Security Headers: Missing X-Frame-Options Header',\\
    severity:'INFO',\\
    tag:'security-headers',\\
    t:none"\n\n`;

  rules += `SecRule RESPONSE_HEADERS:X-Content-Type-Options "@eq 0" \\
    "id:${ruleIdBase + 1},phase:4,pass,msg:'Security Headers: Missing X-Content-Type-Options Header',\\
    severity:'INFO',\\
    tag:'security-headers',\\
    t:none"\n\n`;

  return rules;
}

/**
 * Generate rate limiting rules (Enhanced with ModSecurity collections)
 */
function generateRateLimitingRules(ruleIdBase, rateLimitingConfig) {
  const {
    requestsPerMinute = 60,
    requestsPerHour = 1000,
    burstSize = 10,
  } = rateLimitingConfig;

  let rules = '# Enhanced Rate Limiting Rules\n';
  
  // Initialize rate limiting collections
  rules += `SecAction \\
    "id:${ruleIdBase},phase:1,nolog,pass,t:none,\\
    initcol:ip=%{REMOTE_ADDR},\\
    setvar:'tx.rate_limit_requests_per_minute=${requestsPerMinute}',\\
    setvar:'tx.rate_limit_requests_per_hour=${requestsPerHour}',\\
    setvar:'tx.rate_limit_burst_size=${burstSize}'"\n\n`;

  // Per-minute rate limiting
  rules += `SecAction \\
    "id:${ruleIdBase + 1},phase:1,nolog,pass,t:none,\\
    setvar:'ip.rate_limit_minute=+1',\\
    expirevar:'ip.rate_limit_minute=60'"\n\n`;

  rules += `SecRule IP:rate_limit_minute "@gt ${requestsPerMinute}" \\
    "id:${ruleIdBase + 2},phase:1,block,msg:'Rate Limit Exceeded: Too Many Requests Per Minute (${requestsPerMinute} req/min)',\\
    logdata:'IP: %{REMOTE_ADDR}, Count: %{ip.rate_limit_minute}',\\
    severity:'WARNING',\\
    tag:'rate-limit',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/PROTECTION/DOS',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}',\\
    setvar:'tx.dos_score=+1'"\n\n`;

  // Per-hour rate limiting
  rules += `SecAction \\
    "id:${ruleIdBase + 3},phase:1,nolog,pass,t:none,\\
    setvar:'ip.rate_limit_hour=+1',\\
    expirevar:'ip.rate_limit_hour=3600'"\n\n`;

  rules += `SecRule IP:rate_limit_hour "@gt ${requestsPerHour}" \\
    "id:${ruleIdBase + 4},phase:1,block,msg:'Rate Limit Exceeded: Too Many Requests Per Hour (${requestsPerHour} req/hour)',\\
    logdata:'IP: %{REMOTE_ADDR}, Count: %{ip.rate_limit_hour}',\\
    severity:'WARNING',\\
    tag:'rate-limit',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/PROTECTION/DOS',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}',\\
    setvar:'tx.dos_score=+1'"\n\n`;

  // Burst protection
  rules += `SecAction \\
    "id:${ruleIdBase + 5},phase:1,nolog,pass,t:none,\\
    setvar:'ip.rate_limit_burst=+1',\\
    expirevar:'ip.rate_limit_burst=10'"\n\n`;

  rules += `SecRule IP:rate_limit_burst "@gt ${burstSize}" \\
    "id:${ruleIdBase + 6},phase:1,block,msg:'Rate Limit Exceeded: Burst Size Exceeded (${burstSize} req/10s)',\\
    logdata:'IP: %{REMOTE_ADDR}, Burst: %{ip.rate_limit_burst}',\\
    severity:'WARNING',\\
    tag:'rate-limit',\\
    tag:'OWASP_CRS',\\
    tag:'OWASP_CRS/PROTECTION/DOS',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  return rules;
}

/**
 * Generate IP Access Control rules (Whitelisting/Blacklisting)
 */
function generateIPAccessControlRules(ruleIdBase, ipAccessControl) {
  const { whitelist = [], blacklist = [], action = 'block' } = ipAccessControl;
  let rules = '# IP Access Control Rules\n';
  const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const normalizeIpList = (items = []) =>
    items
      .map((item) => String(item || '').trim())
      .filter(Boolean);

  // IP Whitelist (allow only specified IPs)
  const normalizedWhitelist = normalizeIpList(whitelist);
  if (normalizedWhitelist.length > 0) {
    const ipList = normalizedWhitelist.map(escapeRegex).join('|');
    rules += `SecRule REMOTE_ADDR "!@rx ^(?:${ipList})$" \\
    "id:${ruleIdBase},phase:1,block,msg:'IP Access Control: IP Address Not Whitelisted',\\
    logdata:'IP: %{REMOTE_ADDR}',\\
    severity:'CRITICAL',\\
    tag:'access-control',\\
    tag:'ip-whitelist',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
  }

  // IP Blacklist (block specified IPs)
  const normalizedBlacklist = normalizeIpList(blacklist);
  if (normalizedBlacklist.length > 0) {
    const ipList = normalizedBlacklist.map(escapeRegex).join('|');
    rules += `SecRule REMOTE_ADDR "@rx ^(?:${ipList})$" \\
    "id:${ruleIdBase + 1},phase:1,block,msg:'IP Access Control: IP Address Blacklisted',\\
    logdata:'IP: %{REMOTE_ADDR}',\\
    severity:'CRITICAL',\\
    tag:'access-control',\\
    tag:'ip-blacklist',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
  }

  // CIDR block support for whitelist
  if (ipAccessControl.whitelistCIDR && Array.isArray(ipAccessControl.whitelistCIDR)) {
    ipAccessControl.whitelistCIDR.forEach((cidr, index) => {
      rules += `SecRule REMOTE_ADDR "!@ipMatch ${cidr}" \\
    "id:${ruleIdBase + 10 + index},phase:1,block,msg:'IP Access Control: IP Not in Whitelisted CIDR Block',\\
    logdata:'IP: %{REMOTE_ADDR}, CIDR: ${cidr}',\\
    severity:'CRITICAL',\\
    tag:'access-control',\\
    tag:'ip-whitelist-cidr',\\
    t:none"\n\n`;
    });
  }

  // CIDR block support for blacklist
  if (ipAccessControl.blacklistCIDR && Array.isArray(ipAccessControl.blacklistCIDR)) {
    ipAccessControl.blacklistCIDR.forEach((cidr, index) => {
      rules += `SecRule REMOTE_ADDR "@ipMatch ${cidr}" \\
    "id:${ruleIdBase + 20 + index},phase:1,block,msg:'IP Access Control: IP in Blacklisted CIDR Block',\\
    logdata:'IP: %{REMOTE_ADDR}, CIDR: ${cidr}',\\
    severity:'CRITICAL',\\
    tag:'access-control',\\
    tag:'ip-blacklist-cidr',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
    });
  }

  return rules;
}

/**
 * Generate Geographic Blocking rules
 */
function generateGeoBlockingRules(ruleIdBase, geoBlocking) {
  const { blockedCountries = [], allowedCountries = [], action = 'block' } = geoBlocking;
  let rules = '# Geographic Blocking Rules\n';

  rules += `SecAction "id:${ruleIdBase},phase:1,pass,nolog,t:none,setvar:'tx.geo_country=%{request_headers.cf-ipcountry}'"\n`;
  rules += `SecRule TX:GEO_COUNTRY "@rx ^$" "id:${ruleIdBase + 1},phase:1,pass,nolog,t:none,setvar:'tx.geo_country=%{request_headers.x-vercel-ip-country}'"\n`;
  rules += `SecRule TX:GEO_COUNTRY "@rx ^$" "id:${ruleIdBase + 2},phase:1,pass,nolog,t:none,setvar:'tx.geo_country=%{request_headers.x-geo-country}'"\n\n`;

  if (blockedCountries.length > 0) {
    const countryCodes = blockedCountries.join('|').toUpperCase();
    rules += `SecRule TX:GEO_COUNTRY "@rx ^(?:${countryCodes})$" \\
    "id:${ruleIdBase + 3},phase:1,block,msg:'Geographic Blocking: Request from Blocked Country',\\
    logdata:'Country: %{tx.geo_country}, IP: %{REMOTE_ADDR}',\\
    severity:'WARNING',\\
    tag:'geo-blocking',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
  }

  if (allowedCountries.length > 0) {
    const countryCodes = allowedCountries.join('|').toUpperCase();
    rules += `SecRule TX:GEO_COUNTRY "!@rx ^(?:${countryCodes})$" \\
    "id:${ruleIdBase + 4},phase:1,block,msg:'Geographic Blocking: Request from Non-Allowed Country',\\
    logdata:'Country: %{tx.geo_country}, IP: %{REMOTE_ADDR}',\\
    severity:'WARNING',\\
    tag:'geo-blocking',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
  }

  return rules;
}

/**
 * Generate Advanced Rate Limiting rules (Per-Endpoint, Per-User)
 */
function generateAdvancedRateLimitingRules(ruleIdBase, advancedRateLimiting) {
  const {
    perEndpoint = {},
    perUser = {},
    adaptive = false,
    burstProtection = true,
  } = advancedRateLimiting;

  let rules = '# Advanced Rate Limiting Rules\n';

  // Per-Endpoint Rate Limiting
  if (Object.keys(perEndpoint).length > 0) {
    rules += '# Per-Endpoint Rate Limiting\n';
    Object.entries(perEndpoint).forEach(([endpoint, config], index) => {
      const { requestsPerMinute = 60, requestsPerHour = 1000 } = config;
      const endpointPattern = endpoint.replace(/\//g, '\\/').replace(/\*/g, '.*');
      
      rules += `SecRule REQUEST_URI "@rx ${endpointPattern}" \\
    "id:${ruleIdBase + index * 10},phase:1,nolog,pass,t:none,\\
    setvar:'ip.endpoint_rate_${index}=+1',\\
    expirevar:'ip.endpoint_rate_${index}=60'"\n\n`;

      rules += `SecRule REQUEST_URI "@rx ${endpointPattern}" \\
    "id:${ruleIdBase + index * 10 + 1},phase:1,block,msg:'Advanced Rate Limiting: Endpoint Rate Limit Exceeded',\\
    logdata:'Endpoint: ${endpoint}, IP: %{REMOTE_ADDR}, Count: %{ip.endpoint_rate_${index}}',\\
    severity:'WARNING',\\
    tag:'rate-limit',\\
    tag:'endpoint-rate-limit',\\
    chain"\n`;
      rules += `SecRule IP:endpoint_rate_${index} "@gt ${requestsPerMinute}" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
    });
  }

  // Per-User Rate Limiting (based on session/user ID)
  if (Object.keys(perUser).length > 0) {
    rules += '# Per-User Rate Limiting is not emitted in embedded/native proxy mode because USER collections are not stable there.\n';
    rules += '# Keep per-user limits disabled unless enforcement is moved to an external store or the app layer.\n\n';
  }

  // Adaptive Rate Limiting (adjusts based on attack patterns)
  if (adaptive) {
    rules += '# Adaptive Rate Limiting\n';
    rules += `SecRule TX:ANOMALY_SCORE "@gt 10" \\
    "id:${ruleIdBase + 200},phase:1,nolog,pass,t:none,\\
    setvar:'ip.adaptive_rate_limit=+5',\\
    expirevar:'ip.adaptive_rate_limit=300'"\n\n`;

    rules += `SecRule IP:adaptive_rate_limit "@gt 50" \\
    "id:${ruleIdBase + 201},phase:1,block,msg:'Adaptive Rate Limiting: High Anomaly Score Detected',\\
    logdata:'IP: %{REMOTE_ADDR}, Adaptive Score: %{ip.adaptive_rate_limit}',\\
    severity:'WARNING',\\
    tag:'rate-limit',\\
    tag:'adaptive-rate-limit',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
  }

  return rules;
}

/**
 * Generate Bot Detection and Mitigation rules
 */
function generateBotDetectionRules(ruleIdBase, botDetection) {
  const {
    userAgentFiltering = true,
    botSignatureDetection = true,
    crawlerBlocking = false,
    challengeResponse = false,
  } = botDetection;

  let rules = '# Bot Detection and Mitigation Rules\n';

  // User-Agent filtering
  if (userAgentFiltering) {
    rules += `SecRule REQUEST_HEADERS:User-Agent "@rx ^$" \\
    "id:${ruleIdBase},phase:1,block,msg:'Bot Detection: Missing User-Agent Header',\\
    severity:'WARNING',\\
    tag:'bot-detection',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

    rules += `SecRule REQUEST_HEADERS:User-Agent "@rx (?i)(?:bot|crawler|spider|scraper|curl|wget|python|java|go-http|httpclient|okhttp|apache|libwww)" \\
    "id:${ruleIdBase + 1},phase:1,pass,msg:'Bot Detection: Bot User-Agent Detected',\\
    logdata:'User-Agent: %{MATCHED_VAR}',\\
    severity:'INFO',\\
    tag:'bot-detection',\\
    t:none,\\
    setvar:'tx.bot_detected=1'"\n\n`;
  }

  // Bot signature detection
  if (botSignatureDetection) {
    rules += `SecRule REQUEST_HEADERS "@rx (?i)(?:^Accept:.*text/html|^Accept-Language:.*|^Accept-Encoding:.*gzip)" \\
    "id:${ruleIdBase + 2},phase:1,pass,t:none,\\
    setvar:'tx.bot_score=+1'"\n\n`;

    rules += `SecRule REQUEST_HEADERS:Accept "@rx ^\\*\\/\\*$" \\
    "id:${ruleIdBase + 3},phase:1,block,msg:'Bot Detection: Suspicious Accept Header',\\
    logdata:'Accept: %{MATCHED_VAR}',\\
    severity:'WARNING',\\
    tag:'bot-detection',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

    rules += `SecRule TX:BOT_DETECTED "@eq 1" \\
    "id:${ruleIdBase + 6},phase:1,block,msg:'Bot Detection: Automated Client Blocked',\\
    severity:'WARNING',\\
    tag:'bot-detection',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
  }

  // Crawler blocking
  if (crawlerBlocking) {
    rules += `SecRule TX:BOT_DETECTED "@eq 1" \\
    "id:${ruleIdBase + 4},phase:1,block,msg:'Bot Detection: Crawler Blocked',\\
    logdata:'IP: %{REMOTE_ADDR}',\\
    severity:'WARNING',\\
    tag:'bot-detection',\\
    tag:'crawler-blocked',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
  }

  // Challenge-response (CAPTCHA-like)
  if (challengeResponse) {
    rules += `SecRule TX:BOT_DETECTED "@eq 1" \\
    "id:${ruleIdBase + 5},phase:1,block,msg:'Bot Detection: Challenge Response Required',\\
    severity:'INFO',\\
    tag:'bot-detection',\\
    tag:'challenge-response',\\
    t:none,\\
    setvar:'tx.challenge_required=1'"\n\n`;
  }

  return rules;
}

/**
 * Generate Advanced File Upload Validation rules
 */
function generateAdvancedFileUploadRules(ruleIdBase, advancedFileUpload) {
  const {
    mimeTypeValidation = true,
    contentScanning = true,
    maxFileSize = 10485760, // 10MB default
    allowedExtensions = [],
    blockedExtensions = [],
    virusScanning = false,
  } = advancedFileUpload;

  let rules = '# Advanced File Upload Validation Rules\n';

  // File size validation
  rules += `SecRule FILES "@gt ${maxFileSize}" \\
    "id:${ruleIdBase},phase:2,block,msg:'Advanced File Upload: File Size Exceeded',\\
    logdata:'File Size: %{FILES_SIZE}, Max: ${maxFileSize}',\\
    severity:'WARNING',\\
    tag:'file-upload',\\
    tag:'file-size-validation',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;

  // MIME type validation
  if (mimeTypeValidation) {
    const allowedMimeTypes = advancedFileUpload.allowedMimeTypes || [
      'image/jpeg', 'image/png', 'image/gif', 'application/pdf',
      'text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    ];
    const mimePattern = allowedMimeTypes.join('|').replace(/\//g, '\\/');

    rules += `SecRule REQUEST_HEADERS:Content-Type "!@rx ^(?:multipart/form-data|application/x-www-form-urlencoded)" \\
    "id:${ruleIdBase + 1},phase:2,pass,t:none"\n\n`;

    rules += `SecRule FILES_NAMES "@rx .+" \\
    "id:${ruleIdBase + 2},phase:2,block,msg:'Advanced File Upload: Invalid MIME Type',\\
    logdata:'MIME Type: %{FILES_CONTENT_TYPE}',\\
    severity:'WARNING',\\
    tag:'file-upload',\\
    tag:'mime-type-validation',\\
    chain"\n`;
    rules += `SecRule FILES_CONTENT_TYPE "!@rx ^(?:${mimePattern})$" \\
    "t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
  }

  // Extension validation
  if (allowedExtensions.length > 0) {
    const extPattern = allowedExtensions.map(ext => ext.replace(/\./g, '\\.')).join('|');
    rules += `SecRule FILES_NAMES "!@rx \\.(?:${extPattern})$" \\
    "id:${ruleIdBase + 3},phase:2,block,msg:'Advanced File Upload: File Extension Not Allowed',\\
    logdata:'File: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'file-upload',\\
    tag:'extension-validation',\\
    t:none,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
  }

  if (blockedExtensions.length > 0) {
    const extPattern = blockedExtensions.map(ext => ext.replace(/\./g, '\\.')).join('|');
    rules += `SecRule FILES_NAMES "@rx \\.(?:${extPattern})$" \\
    "id:${ruleIdBase + 4},phase:2,block,msg:'Advanced File Upload: Blocked File Extension',\\
    logdata:'File: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'file-upload',\\
    tag:'extension-blocked',\\
    t:none,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
  }

  // Content scanning (magic bytes validation)
  if (contentScanning) {
    rules += `# Content Scanning: Magic Bytes Validation\n`;
    rules += `# Note: Requires file content inspection\n`;
    rules += `SecRule FILES_TMPNAMES "@rx .+" \\
    "id:${ruleIdBase + 5},phase:2,pass,msg:'Advanced File Upload: Content Scanning Required',\\
    severity:'INFO',\\
    tag:'file-upload',\\
    tag:'content-scanning',\\
    t:none"\n\n`;
  }

  return rules;
}

/**
 * Generate API-Specific Protection rules
 */
function generateAPIProtectionRules(ruleIdBase, apiProtection) {
  const {
    apiKeyValidation = false,
    apiKeyHeader = 'X-API-Key',
    oauthValidation = false,
    jwtValidation = false,
    apiVersioning = false,
    requestSigning = false,
  } = apiProtection;

  let rules = '# API-Specific Protection Rules\n';

  // API Key validation
  if (apiKeyValidation) {
    const validApiKeys = apiProtection.validApiKeys || [];
    if (validApiKeys.length > 0) {
      const keyPattern = validApiKeys.join('|').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      rules += `SecRule REQUEST_HEADERS:${apiKeyHeader} "!@rx ^(?:${keyPattern})$" \\
    "id:${ruleIdBase},phase:1,block,msg:'API Protection: Invalid API Key',\\
    logdata:'API Key: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'api-protection',\\
    tag:'api-key-validation',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
    } else {
      rules += `SecRule REQUEST_HEADERS:${apiKeyHeader} "@rx ^$" \\
    "id:${ruleIdBase},phase:1,block,msg:'API Protection: Missing API Key',\\
    severity:'CRITICAL',\\
    tag:'api-protection',\\
    tag:'api-key-missing',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
    }
  }

  // OAuth token validation
  if (oauthValidation) {
    rules += `SecRule REQUEST_HEADERS:Authorization "@rx ^$" \\
    "id:${ruleIdBase + 1},phase:1,block,msg:'API Protection: Missing OAuth Bearer Token',\\
    severity:'CRITICAL',\\
    tag:'api-protection',\\
    tag:'oauth-validation',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

    rules += `SecRule REQUEST_HEADERS:Authorization "!@rx ^Bearer\\s+[A-Za-z0-9\\-\\._~\\+\\/]+=*$" \\
    "id:${ruleIdBase + 2},phase:1,block,msg:'API Protection: Invalid OAuth Token Format',\\
    logdata:'Authorization: %{MATCHED_VAR}',\\
    severity:'CRITICAL',\\
    tag:'api-protection',\\
    tag:'oauth-validation',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
  }

  // JWT validation
  if (jwtValidation) {
    rules += `SecRule REQUEST_HEADERS:Authorization "@rx ^$" \\
    "id:${ruleIdBase + 3},phase:1,block,msg:'API Protection: Missing JWT Bearer Token',\\
    severity:'CRITICAL',\\
    tag:'api-protection',\\
    tag:'jwt-validation',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;

    rules += `SecRule REQUEST_HEADERS:Authorization "@rx ^Bearer\\s+([A-Za-z0-9\\-\\._~\\+\\/]+=*)" \\
    "id:${ruleIdBase + 4},phase:1,pass,capture,t:none,\\
    setvar:'tx.jwt_token=%{TX.1}'"\n\n`;

    rules += `SecRule TX:JWT_TOKEN "!@rx ^[A-Za-z0-9\\-\\._~\\+\\/]+=*\\.[A-Za-z0-9\\-\\._~\\+\\/]+=*\\.[A-Za-z0-9\\-\\._~\\+\\/]+=*$" \\
    "id:${ruleIdBase + 5},phase:1,block,msg:'API Protection: Invalid JWT Format',\\
    logdata:'JWT: %{tx.jwt_token}',\\
    severity:'CRITICAL',\\
    tag:'api-protection',\\
    tag:'jwt-validation',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
  }

  // API versioning
  if (apiVersioning) {
    const allowedVersions = apiProtection.allowedVersions || ['v1', 'v2'];
    const versionPattern = allowedVersions.join('|');
    rules += `SecRule REQUEST_URI|REQUEST_HEADERS:API-Version "@rx (?:v\\d+|version=\\d+)" \\
    "id:${ruleIdBase + 6},phase:1,pass,capture,t:none,\\
    setvar:'tx.api_version=%{TX.0}'"\n\n`;

    rules += `SecRule TX:API_VERSION "!@rx ^(?:${versionPattern})$" \\
    "id:${ruleIdBase + 7},phase:1,block,msg:'API Protection: Unsupported API Version',\\
    logdata:'Version: %{tx.api_version}',\\
    severity:'WARNING',\\
    tag:'api-protection',\\
    tag:'api-versioning',\\
    t:none,\\
    setvar:'tx.anomaly_score=+%{tx.warning_anomaly_score}'"\n\n`;
  }

  return rules;
}

/**
 * Generate Exception Rules (Rule Exclusions)
 */
function generateExceptionRules(ruleIdBase, exceptions) {
  let rules = '# Exception Rules (Rule Exclusions)\n';

  exceptions.forEach((exception, index) => {
    const { path, ruleIds = [], reason = 'Exception rule' } = exception;
    const pathPattern = path.replace(/\//g, '\\/').replace(/\*/g, '.*');

    if (ruleIds.length > 0) {
      const ruleIdList = ruleIds.join(',');
      rules += `# Exception: ${reason}\n`;
      rules += `SecRule REQUEST_URI "@rx ^${pathPattern}" \\
    "id:${ruleIdBase + index},phase:1,nolog,pass,t:none,\\
    ctl:ruleRemoveById=${ruleIdList}"\n\n`;
    } else {
      rules += `# Exception skipped for ${reason}: explicit rule IDs are required for production safety\n\n`;
    }
  });

  return rules;
}

/**
 * Generate Virtual Patching rules (CVE-Specific)
 */
function generateVirtualPatchingRules(ruleIdBase, virtualPatching) {
  let rules = '# Virtual Patching Rules (CVE-Specific)\n';

  virtualPatching.forEach((patch, index) => {
    const { cve, description, pattern, severity = 'CRITICAL' } = patch;
    const ruleId = ruleIdBase + index * 10;
    const safeCve = escapeActionValue(cve);
    const safeDescription = escapeActionValue(description);
    const safePattern = escapeRegexPattern(pattern);
    const safeSeverity = escapeActionValue(severity);

    rules += `# Virtual Patch: ${safeCve} - ${safeDescription}\n`;
    rules += `SecRule ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|REQUEST_HEADERS|XML:/* "@rx ${safePattern}" \\
    "id:${ruleId},phase:2,block,msg:'Virtual Patch: ${safeCve} - ${safeDescription}',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'${safeSeverity}',\\
    tag:'virtual-patch',\\
    tag:'cve-${safeCve}',\\
    t:none,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\\
    setvar:'tx.anomaly_score=+%{tx.critical_anomaly_score}'"\n\n`;
  });

  return rules;
}

/**
 * Generate custom rule
 */
function generateCustomRule(rule, ruleId) {
  const {
    phase = 2,
    action = 'block',
    msg = 'Custom Rule Triggered',
    severity = 'WARNING',
    tag = 'custom',
    variables = 'ARGS',
    pattern = '',
    transformations = 't:none',
  } = rule;
  const safeVariables = String(variables || 'ARGS').replace(/\r?\n/g, ' ');
  const safePattern = escapeRegexPattern(pattern);
  const safeMsg = escapeActionValue(msg);
  const safeSeverity = escapeActionValue(severity);
  const safeTag = escapeActionValue(tag);
  const safeTransformations = String(transformations || 't:none').replace(/\r?\n/g, ' ');
  const safeAction = String(action || 'block').replace(/\r?\n/g, ' ');

  return `SecRule ${safeVariables} "@rx ${safePattern}" \\
    "id:${ruleId},phase:${phase},${safeAction},msg:'${safeMsg}',\\
    severity:'${safeSeverity}',\\
    tag:'${safeTag}',\\
    ${safeTransformations}"\n\n`;
}

/**
 * Validate ModSecurity configuration syntax
 * @param {string} config - ModSecurity configuration to validate
 * @returns {Object} Validation result
 */
export function validateModSecurityConfig(config) {
  const errors = [];
  const warnings = [];

  // Basic syntax checks
  const lines = config.split('\n');
  let inChain = false;

  lines.forEach((line, index) => {
    const trimmed = line.trim();

    // Skip comments and empty lines
    if (trimmed.startsWith('#') || trimmed === '') {
      return;
    }

    // Check SecRule directives only (skip SecRuleEngine, etc.)
    if (/^SecRule\s+/.test(trimmed)) {
      // Most generated rules place action list (id/phase/chain) on the next line.
      // Validate using a short lookahead window instead of the current line only.
      const lookahead = lines.slice(index, Math.min(index + 15, lines.length)).join(' ');
      const hasId = /\bid:\d+\b/.test(lookahead);
      const hasPhase = /\bphase:\d+\b/.test(lookahead);
      const hasChain = /\bchain\b/.test(lookahead);

      // Chained sub-rules are allowed to omit id/phase.
      if (!inChain && !hasId) {
        errors.push(`Line ${index + 1}: SecRule missing id parameter`);
      }
      if (!inChain && !hasPhase) {
        warnings.push(`Line ${index + 1}: SecRule missing phase parameter`);
      }

      inChain = hasChain;
      return;
    }

    // Check SecAction syntax
    if (/^SecAction\s+/.test(trimmed)) {
      const lookahead = lines.slice(index, Math.min(index + 3, lines.length)).join(' ');
      if (!/\bid:\d+\b/.test(lookahead)) {
        errors.push(`Line ${index + 1}: SecAction missing id parameter`);
      }
      inChain = false;
      return;
    }

    // Reset chain state when a new directive begins.
    if (/^Sec[A-Za-z]/.test(trimmed)) {
      inChain = false;
    }
  });

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

/**
 * Extract rule IDs from configuration
 * @param {string} config - ModSecurity configuration
 * @returns {Array<number>} Array of rule IDs
 */
export function extractRuleIds(config) {
  const ruleIdRegex = /"id:(\d+)/g;
  const ruleIds = [];
  let match;

  while ((match = ruleIdRegex.exec(config)) !== null) {
    ruleIds.push(parseInt(match[1], 10));
  }

  return ruleIds.sort((a, b) => a - b);
}

/**
 * Get OWASP CRS rule set information
 * @returns {Object} CRS information
 */
export function getOWASPCRSInfo() {
  return {
    version: '3.3.0',
    description: 'OWASP ModSecurity Core Rule Set',
    rules: [
      'REQUEST-901-INITIALIZATION',
      'REQUEST-905-COMMON-EXCEPTIONS',
      'REQUEST-910-IP-REPUTATION',
      'REQUEST-911-METHOD-ENFORCEMENT',
      'REQUEST-912-DOS-PROTECTION',
      'REQUEST-913-SCANNER-DETECTION',
      'REQUEST-920-PROTOCOL-ENFORCEMENT',
      'REQUEST-921-PROTOCOL-ATTACK',
      'REQUEST-930-APPLICATION-ATTACK-LFI',
      'REQUEST-931-APPLICATION-ATTACK-RFI',
      'REQUEST-932-APPLICATION-ATTACK-RCE',
      'REQUEST-933-APPLICATION-ATTACK-PHP',
      'REQUEST-934-APPLICATION-ATTACK-NODEJS',
      'REQUEST-941-APPLICATION-ATTACK-XSS',
      'REQUEST-942-APPLICATION-ATTACK-SQLI',
      'REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION',
      'REQUEST-944-APPLICATION-ATTACK-JAVA',
      'REQUEST-949-BLOCKING-EVALUATION',
      'RESPONSE-950-DATA-LEAKAGES',
      'RESPONSE-951-DATA-LEAKAGES-SQL',
      'RESPONSE-952-DATA-LEAKAGES-JAVA',
      'RESPONSE-953-DATA-LEAKAGES-PHP',
      'RESPONSE-954-DATA-LEAKAGES-IIS',
      'RESPONSE-959-BLOCKING-EVALUATION',
      'RESPONSE-980-CORRELATION',
    ],
    enhancedProtections: [
      'CSRF Protection',
      'Session Fixation Protection',
      'SSRF Protection',
      'XXE Protection',
      'Authentication Bypass Protection',
      'IDOR Protection',
      'Security Misconfiguration Detection',
      'Sensitive Data Exposure Protection',
      'Broken Access Control Protection',
      'Security Headers Enforcement',
      'Enhanced Rate Limiting',
      'Enhanced SQL Injection Detection',
      'Enhanced XSS Detection',
    ],
  };
}

function sanitizeConfigForProxy(fullConfig, { stripIncludes = true } = {}) {
  if (!fullConfig || typeof fullConfig !== 'string') return '';

  const unsupportedDirectivePatterns = [
    /^\s*SecTmpDir\b/i,
    /^\s*SecDataDir\b/i,
    /^\s*SecUploadDir\b/i,
    /^\s*SecUploadFileMode\b/i,
    /^\s*SecTmpSaveUploadedFiles\b/i,
    /^\s*SecAuditEngine\b/i,
    /^\s*SecAuditLog\b/i,
    /^\s*SecAuditLogType\b/i,
    /^\s*SecAuditLogParts\b/i,
    /^\s*SecAuditLogRelevantStatus\b/i,
    /^\s*SecAuditLogFileReopenLimit\b/i,
    /^\s*SecAuditLogStorageDir\b/i,
    /^\s*SecAuditLogFileMode\b/i,
    /^\s*SecAuditLogDirMode\b/i,
    /^\s*SecAuditLogDirPermissions\b/i,
  ];

  return fullConfig
    .split('\n')
    .map((line) => line.replace(/\bauditlog\b,?/gi, '').replace(/,,+/g, ',').replace(/,\s*"/g, '"'))
    .filter((line) => {
      const trimmed = line.trim();
      if (stripIncludes && /^\s*Include\s+/i.test(trimmed)) return false;
      if (unsupportedDirectivePatterns.some((pattern) => pattern.test(trimmed))) return false;
      if (/\bsetenv:/i.test(trimmed)) return false;
      // The embedded Rules.add() path is not stable with custom user/resource collections.
      if (/\b(?:setvar|expirevar|deprecatevar):'user\./i.test(trimmed)) return false;
      if (/^\s*SecRule\s+USER:/i.test(trimmed)) return false;
      return true;
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function extractIncludePaths(fullConfig) {
  return String(fullConfig || '')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => /^\s*Include\s+/i.test(line))
    .map((line) => line.replace(/^\s*Include\s+/i, '').trim())
    .filter(Boolean);
}

export function getNativeConfigCandidates(fullConfig) {
  if (!fullConfig || typeof fullConfig !== 'string') return [];

  const includePaths = extractIncludePaths(fullConfig);
  const includePathsAvailable =
    includePaths.length > 0 && includePaths.every((includePath) => existsSync(includePath));

  const candidates = [];

  if (includePathsAvailable) {
    const fullNativeConfig = sanitizeConfigForProxy(fullConfig, { stripIncludes: false });
    if (fullNativeConfig) {
      candidates.push({
        name: 'libmodsecurity-crs',
        config: fullNativeConfig,
      });
    }
  }

  const strippedConfig = sanitizeConfigForProxy(fullConfig, { stripIncludes: true });
  if (strippedConfig) {
    candidates.push({
      name: 'standalone-no-crs',
      config: strippedConfig,
    });
  }

  return candidates;
}

/**
 * Produce a proxy-safe ModSecurity config usable by libmodsecurity Rules.add()
 * Strips Include directives so rules work without CRS on disk.
 * @param {string} fullConfig - Full config (may contain Include /path/to/crs)
 * @returns {string} Config with Include lines removed, suitable for rules.add()
 */
export function getStandaloneConfigForProxy(fullConfig) {
  return sanitizeConfigForProxy(fullConfig, { stripIncludes: true });
}
